name: Build Flutter APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0'
          channel: 'stable'
          cache: true
      
      - name: Create android folder
        run: flutter create . --platforms android --project-name homa_amlak
      
      - name: Patch Android Configurations (Fix SDK, Kotlin & Permissions)
        run: |
          # ۱. تغییر نسخه Android SDK به ۳۵ برای سازگاری با image_picker
          sed -i 's/compileSdk flutter.compileSdkVersion/compileSdk 35/g' android/app/build.gradle
          sed -i 's/compileSdkVersion flutter.compileSdkVersion/compileSdkVersion 35/g' android/app/build.gradle
          
          # ۲. تغییر نسخه Kotlin به 1.9.24
          sed -i "s/ext.kotlin_version = '.*'/ext.kotlin_version = '1.9.24'/g" android/build.gradle
          
          # ۳. اضافه کردن مجوزهای ضروری دوربین و گالری به AndroidManifest.xml
          MANIFEST="android/app/src/main/AndroidManifest.xml"
          sed -i '/<application>/i \    <uses-permission android:name="android.permission.CAMERA"/>\n    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" android:maxSdkVersion="32"/>\n    <uses-permission android:name="android.permission.READ_MEDIA_IMAGES"/>' $MANIFEST

      - name: Install dependencies
        run: flutter pub get
      
      - name: Build APK
        run: flutter build apk --release
      
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
